Typical scikit-learn workflow

0. Getting the data ready
1. Choose the right estimator / model for our problems
2. Fit the data and use it to make predictions on our data
3. Evaluate a model
4. Improve a model
5. Save and reload a trained model

In [5]:
workflow = [
    "0. Getting the data ready",
    "1. Choose the right estimator / model for our problems",
    "2. Fit the data and use it to make predictions on our data",
    "3. Evaluate a model",
    "4. Improve a model",
    "5. Save and reload a trained model"
]

In [6]:
workflow

['0. Getting the data ready',
 '1. Choose the right estimator / model for our problems',
 '2. Fit the data and use it to make predictions on our data',
 '3. Evaluate a model',
 '4. Improve a model',
 '5. Save and reload a trained model']

# Getting the data ready

In [7]:
import warnings 
warnings.filterwarnings(action = "default")

In [8]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

In [9]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators = 100, random_state = 0)
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 0,
 'verbose': 0,
 'warm_start': False}

In [10]:
car_sales_df = pd.read_csv("./data/car-sales-extended.csv")
car_sales_df.head()

     Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [11]:
heart_disease_df = pd.read_csv("./data/heart-disease.csv")
heart_disease_df.head()

   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1        0      150      0      2.3      0   0     1       1
1   37    1   2       130   250    0        1      187      0      3.5      0   0     2       1
2   41    0   1       130   204    0        0      172      0      1.4      2   0     2       1
3   56    1   1       120   236    0        1      178      0      0.8      2   0     2       1
4   57    0   0       120   354    0        1      163      1      0.6      2   0     2       1

### Getting the data ready
    1. Split the data into features and labels ( `X` & `y` )
    2. Filling ( also called imputing ) or disregarding missing values
    3. Converting non numerical values to numerical values ( also called feature encoding )

In [12]:
len(car_sales_df)

1000

In [13]:
len(heart_disease_df)

303

In [14]:
X = heart_disease_df.drop("target", axis = 1)
y = heart_disease_df["target"]

In [15]:
from sklearn.model_selection import train_test_split
X_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [16]:
X_train.shape, x_test.shape

((242, 13), (61, 13))

In [17]:
y_train.shape, y_test.shape

((242,), (61,))

In [18]:
X_train.shape[0] == np.floor(len(heart_disease_df) * 0.8)

np.True_

In [19]:
from sklearn.ensemble import RandomForestRegressor
rg = RandomForestRegressor(n_estimators=100, random_state=0)

In [20]:
X = car_sales_df.drop("Price", axis = 1)
y = car_sales_df["Price"]

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [22]:
rg.fit(X_train, y_train)

ValueError: could not convert string to float: 'Honda'

### Clean, transform & reduce data

In [23]:
# It is also categorical
car_sales_df["Doors"].value_counts()

Doors
4    856
5     79
3     65
Name: count, dtype: int64

### Convert data to numbers

In [34]:
X_train["Colour"].value_counts()

Colour
White    329
Blue     252
Black     81
Red       74
Green     64
Name: count, dtype: int64

In [33]:
X_train.head()

       Make Colour  Odometer (KM)  Doors
194   Honda  White          74192      4
43   Toyota   Blue         141617      4
978     BMW  White          85739      5
970  Toyota   Blue         186309      4
25    Honda   Blue         125819      4

In [42]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
encoder = OneHotEncoder(handle_unknown = "ignore")
preprocessor = ColumnTransformer([("cat", 
                                 encoder,
                                 categorical_features)], 
                                 remainder = "passthrough"  
                                )
transformed_X = preprocessor.fit_transform(X)
transformed_X
pd.DataFrame(transformed_X).head()

    0    1    2    3    4    5    6    7    8    9    10   11        12
0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0

### Another way convert data to numbers

In [39]:
dummies = pd.get_dummies(X_train[["Make", "Colour", "Doors"]])
dummies.head()

     Doors  Make_BMW  Make_Honda  Make_Nissan  ...  Colour_Blue  Colour_Green  Colour_Red  Colour_White
194      4     False        True        False  ...        False         False       False          True
43       4     False       False        False  ...         True         False       False         False
978      5      True       False        False  ...        False         False       False          True
970      4     False       False        False  ...         True         False       False         False
25       4     False        True        False  ...         True         False       False         False

[5 rows x 10 columns]

In [46]:
X_train, X_test, y_train, y_test = train_test_split(transformed_X, y, test_size=0.2)

In [47]:
rg.fit(X_train, y_train)

RandomForestRegressor(random_state=0)

In [48]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [51]:
rg.score(X_train, y_train)

0.8962486293937206

In [50]:
rg.score(X_test, y_test)

0.16368705980985176

In [55]:
# Check scikit-learn version
import sklearn
sklearn.show_versions()

System:
    python: 3.9.25 (main, Nov  3 2025, 22:44:01) [MSC v.1929 64 bit (AMD64)]
executable: C:\Users\Cahangir\Desktop\Data_Science_Course\SKlearn\env\python.exe
   machine: Windows-10-10.0.26200-SP0

Python dependencies:
      sklearn: 1.6.1
          pip: 26.0.1
   setuptools: 72.1.0
        numpy: 2.0.2
        scipy: 1.13.1
       Cython: None
       pandas: 2.3.3
   matplotlib: 3.9.2
       joblib: 1.5.2
threadpoolctl: 3.5.0

Built with OpenMP: True

threadpoolctl info:
       user_api: blas
   internal_api: mkl
    num_threads: 12
         prefix: mkl_rt
       filepath: C:\Users\Cahangir\Desktop\Data_Science_Course\SKlearn\env\Library\bin\mkl_rt.2.dll
        version: 2023.1-Product
threading_layer: intel

       user_api: openmp
   internal_api: openmp
    num_threads: 16
         prefix: vcomp
       filepath: C:\Users\Cahangir\Desktop\Data_Science_Course\SKlearn\env\vcomp140.dll
        version: None