Typical scikit-learn workflow

1. Getting the data ready
2. Choose the right estimator / model for our problems
3. Fit the data and use it to make predictions on our data
4. Evaluate a model
5. Improve a model
6. Save and reload a trained model

In [8]:
workflow = [
    '1. Getting the data ready',
    '2. Choose the right estimator / model for our problems',
    '3. Fit the data and use it to make predictions on our data',
    '4. Evaluate a model',
    '5. Improve a model',
    '6. Save and reload a trained model'
]

In [9]:
workflow

['1. Getting the data ready',
 '2. Choose the right estimator / model for our problems',
 '3. Fit the data and use it to make predictions on our data',
 '4. Evaluate a model',
 '5. Improve a model',
 '6. Save and reload a trained model']

### Getting the data ready

In [10]:
import warnings
warnings.filterwarnings(action = "error")

In [ ]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import sklearn

In [15]:
# Check python version
sklearn.show_versions()

System:
    python: 3.9.25 (main, Nov  3 2025, 22:44:01) [MSC v.1929 64 bit (AMD64)]
executable: C:\Users\Cahangir\Desktop\Data_Science_Course\SKlearn\env\python.exe
   machine: Windows-10-10.0.26200-SP0

Python dependencies:
      sklearn: 1.6.1
          pip: 26.0.1
   setuptools: 72.1.0
        numpy: 2.0.2
        scipy: 1.13.1
       Cython: None
       pandas: 2.3.3
   matplotlib: 3.9.2
       joblib: 1.5.2
threadpoolctl: 3.5.0

Built with OpenMP: True

threadpoolctl info:
       user_api: blas
   internal_api: mkl
    num_threads: 12
         prefix: mkl_rt
       filepath: C:\Users\Cahangir\Desktop\Data_Science_Course\SKlearn\env\Library\bin\mkl_rt.2.dll
        version: 2023.1-Product
threading_layer: intel

       user_api: openmp
   internal_api: openmp
    num_threads: 16
         prefix: vcomp
       filepath: C:\Users\Cahangir\Desktop\Data_Science_Course\SKlearn\env\vcomp140.dll
        version: None

In [13]:
car_sales_missing_df = pd.read_csv("./data/car-sales-extended-missing-data.csv")
car_sales_missing_df.head()

     Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [16]:
len(car_sales_missing_df)

1000

In [19]:
# How many missing values are there ?
car_sales_missing_df.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [26]:
# Option 1: Handling missing values with pandas
car_sales_missing_df["Make"].fillna("Missing", inplace=True)

car_sales_missing_df["Colour"].fillna("Missing", inplace=True)

car_sales_missing_df["Doors"].fillna(4, inplace=True)

car_sales_missing_df['Odometer (KM)'].fillna(car_sales_missing_df['Odometer (KM)'].mean(), inplace=True);

In [32]:
# Check how many missing values are there again
car_sales_missing_df.isna().sum()

Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

In [38]:
# Delete rows with NaN in the Price column
car_sales_missing_df.dropna(inplace=True)

In [39]:
# Check how many missing values are there again
car_sales_missing_df.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [69]:
# Split the data into features and labels
X = car_sales_missing_df.drop("Price", axis = 1)
y = car_sales_missing_df["Price"]
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
rg = RandomForestRegressor(random_state=42)

In [85]:
# Future encoding
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
encoder = OneHotEncoder(handle_unknown = "ignore")
# scaler = MinMaxScaler()
scaler = StandardScaler()
categorical_columns = ["Make", "Colour", "Doors"]
numerical_columns = ["Odometer (KM)"]
preprocessor = ColumnTransformer([
    ("Cat",
    encoder,
    categorical_columns),
    ("Num", 
    scaler,
    numerical_columns)
], remainder="passthrough")
transformed_X = preprocessor.fit_transform(X)
pd.DataFrame(transformed_X).head()

                                                   0
0    (np.int32(0), np.int32(1))\t1.0\n  (np.int32...
1    (np.int32(0), np.int32(0))\t1.0\n  (np.int32...
2    (np.int32(0), np.int32(1))\t1.0\n  (np.int32...
3    (np.int32(0), np.int32(4))\t1.0\n  (np.int32...
4    (np.int32(0), np.int32(3))\t1.0\n  (np.int32...

In [86]:
X_train, X_test, y_train, y_test = train_test_split(transformed_X, y, test_size=0.2)
rg.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [87]:
rg.score(X_test, y_test)

0.31355148303875147

In [88]:
for i in range(10, 110, 10):
    rg = RandomForestRegressor(n_estimators=i, random_state=42)
    rg.fit(X_train, y_train)
    print(rg.score(X_test, y_test))

0.2256374358366282
0.28712731661168345
0.29676947456162583
0.29956268030135214
0.30830125064136193
0.30484192455265546
0.3123084407624931
0.3175765336170413
0.31389475101294695
0.31355148303875147