In [1]:
import numpy as np
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
car_datas = pd.read_csv("car-sales.csv")
car_datas

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [8]:
car_datas.describe()

       Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

# Creating NumPy arrays

#### With array method

In [ ]:
a4 = np.array([[1, 2], [3, 4]])
a4

array([[1, 2],
       [3, 4]])

In [16]:
a4.size

4

In [17]:
a4.dtype

dtype('int64')

In [18]:
type(a4)

numpy.ndarray

In [19]:
a4.shape

(2, 2)

In [26]:
a4.ndim

2

#### With DataFrames

In [ ]:
car_ndarray = np.array(car_datas)

In [22]:
car_ndarray

array([['Toyota', 'White', 150043, 4, '$4,000.00'],
       ['Honda', 'Red', 87899, 4, '$5,000.00'],
       ['Toyota', 'Blue', 32549, 3, '$7,000.00'],
       ['BMW', 'Black', 11179, 5, '$22,000.00'],
       ['Nissan', 'White', 213095, 4, '$3,500.00'],
       ['Toyota', 'Green', 99213, 4, '$4,500.00'],
       ['Honda', 'Blue', 45698, 4, '$7,500.00'],
       ['Honda', 'Blue', 54738, 4, '$7,000.00'],
       ['Toyota', 'White', 60000, 4, '$6,250.00'],
       ['Nissan', 'White', 31600, 4, '$9,700.00']], dtype=object)

#### With ones and zeros methods

In [27]:
# Shift + tab ----- open description about methods
ones = np.ones((5,), dtype = "int")
ones

array([1, 1, 1, 1, 1])

In [33]:
# Ones method
ones.dtype

dtype('int64')

In [29]:
type(ones)

numpy.ndarray

In [36]:
# Zeros method
zeros = np.zeros((2, 3), dtype = "int")
zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [42]:
# Range method
range_array = np.arange(0, 10, 2, dtype = "float") 
range_array

array([0., 2., 4., 6., 8.])

In [44]:
# Random module
random_array = np.random.rand(2, 3, 3)
random_array

array([[[0.49331933, 0.39967159, 0.28333851],
        [0.08474255, 0.72970436, 0.70997357],
        [0.70466158, 0.88041911, 0.02386042]],

       [[0.44181309, 0.94885888, 0.67009228],
        [0.08554429, 0.4839013 , 0.12458028],
        [0.63053763, 0.87198478, 0.09724053]]])

In [48]:
random_array = np.random.randint(1, 10, (2, 3))
random_array

array([[4, 2, 3],
       [6, 2, 6]], dtype=int32)

In [49]:
random_array.size

6

In [52]:
# Seed and default_rng
rng = np.random.default_rng(42)
seed_array = rng.uniform(1.2, 100.5, (2, 3))
seed_array

array([[78.05383562, 44.78062907, 86.45877345],
       [70.44864529, 10.55181065, 98.07929952]])

In [54]:
rng = np.random.default_rng(42)
seed_array = rng.uniform(1.2, 100.5, size = (2, 3))
seed_array

array([[78.05383562, 44.78062907, 86.45877345],
       [70.44864529, 10.55181065, 98.07929952]])

In [57]:
# Random method
random_array2 = np.random.random((2, 3, 5))
random_array2

array([[[0.64753088, 0.16904129, 0.60201651, 0.77078172, 0.02567134],
        [0.07135811, 0.85107234, 0.39941947, 0.81072127, 0.02713369],
        [0.43912326, 0.31604318, 0.16740143, 0.77206199, 0.51945861]],

       [[0.85846057, 0.00286672, 0.32066745, 0.24224763, 0.057415  ],
        [0.93825416, 0.74190405, 0.57965915, 0.21018523, 0.3150233 ],
        [0.01717006, 0.39192132, 0.90359923, 0.69776268, 0.94942935]]])

In [74]:
# Examples
rng = np.random.default_rng(40)
random_array_5 = rng.random((2, 3))
random_array_5

array([[0.7298985 , 0.69341496, 0.94192102],
       [0.05965206, 0.69052097, 0.92239752]])

In [81]:
random_array_5 = rng.random((2, 3))
random_array_5

array([[0.19008143, 0.32751391, 0.33118926],
       [0.30748777, 0.11210277, 0.5622017 ]])

In [85]:
# Example about seed ( pseudo-random numbers )
np.random.seed(40)
np.random.random((2,3))

array([[0.40768703, 0.05536604, 0.78853488],
       [0.28730518, 0.45035059, 0.30391231]])